// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://maelrohlhrhihntydydh.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1hZWxyb2hsaHJoaWhudHlkeWRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMwMjA0NzksImV4cCI6MjA0ODU5NjQ3OX0.J5EU9Vb1FzHZYGxnfiE5IWkuTXOIYVJlafVeKGjv8DY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);